sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database:
    username:
    password:

    redis:
      host: localhost
      port: 6379
  #      password : 123456
  #      database: 10  数据源

  #阿里云
#  alioss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    access-key-id:
#    access-key-secret:
#    bucket-name:
#
#  wechat:
#    appid:
#    secret:
